name: release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    working-directory: ./code

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prepare
        run: |
          git fetch --prune --unshallow --tags
          mkdir ./assets

          CURRENT_TAG=$(git tag --points-at HEAD)
          echo ::set-output name=version::${CURRENT_TAG//v}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"

      - name: Install ARM GCC
        run: |
          wget -nv https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          sudo tar -C /bin/ -xjf gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
          echo "MBED_GCC_ARM_PATH=/bin/gcc-arm-none-eabi-9-2019-q4-major/bin/" >> $GITHUB_ENV

      - name: Install Mbed
        run: |
          pip install wheel
          pip install mbed-cli

      - name: Install dependencies
        run: |
          mbed deploy
          cd ./mbed-os && pip install -r requirements.txt

      - name: Build
        if: success()
        run: |
          mbed compile -t GCC_ARM -m SIGFOX_TEMP_V1 --profile release
          mv "./BUILD/SIGFOX_TEMP_V1/GCC_ARM-RELEASE/sigfox-th-sensor.bin" "./assets/FW_${{ steps.prepare.outputs.version }}.bin"

      - name: "Build: verbose"
        if: success()
        run: |
          mbed compile -t GCC_ARM -m SIGFOX_TEMP_V1
          mv "./BUILD/SIGFOX_TEMP_V1/GCC_ARM/sigfox-th-sensor.bin" "./assets/FW_${{ steps.prepare.outputs.version }}_verbose.bin"

      - name: Create release
        if: ${{ success() && steps.prepare.outputs.version != null }}
        run: |
          set -x
          assets=()

          for path in ./assets/*.bin; do
            assets+=("-a" "${path}")
          done

          echo "FW ${{ steps.prepare.outputs.version }}" >"CHANGELOG.md"
          echo "" >>"CHANGELOG.md"
          echo "## :bookmark_tabs: Changes" >>"CHANGELOG.md"
          git log --pretty=format:"- %s %H%n" $(git describe --abbrev=0 --tags $(git describe --tags --abbrev=0)^)...$(git describe --tags --abbrev=0) >>"CHANGELOG.md"

          cat "CHANGELOG.md"

          hub release create "${assets[@]}" "--file" "CHANGELOG.md" "$(git tag --points-at HEAD)"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
